name: CI
on: [push, workflow_dispatch]
jobs:
  integration-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test
    steps:
      - uses: actions/checkout@master
      - run: ./test.sh
